//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System;

[assembly: AssemblyTitle("SqlServerSlackAPI")]
[assembly: AssemblyDescription("SQL Server Slack API")]
[assembly: AssemblyCompany("WCOM AB")]
[assembly: AssemblyProduct("SqlServerSlackAPI")]
[assembly: AssemblyVersion("0.0.2")]
[assembly: AssemblyFileVersion("0.0.2")]
[assembly: AssemblyInformationalVersion("0.0.2")]
[assembly: AssemblyCopyright("Copyright © WCOM AB 2015")]
[assembly: CLSCompliant(true)]

